### ISSUE TITLE
Check failed when testing quantize in JDetNet

### ISSUE THREAD

**Issue by gasburner** [tidsp/caffe-jacinto-models#6] opened 2018-09-10 08:07 UTC
Hello，i run the tarin_image_object_detection.sh, and got some problems in the test_quantize phase.
Here is the log.
I0910 14:36:28.498530 13312 common.cpp:475] GPU 0 'TITAN Xp' has compute capability 6.1
I0910 14:36:29.036025 13312 caffe.cpp:902] This is NVCaffe 0.17.0 started at Mon Sep 10 14:36:28 2018
I0910 14:36:29.036056 13312 caffe.cpp:904] CuDNN version: 7104
I0910 14:36:29.036072 13312 caffe.cpp:905] CuBLAS version: 9000
I0910 14:36:29.036077 13312 caffe.cpp:906] CUDA version: 9000
I0910 14:36:29.036082 13312 caffe.cpp:907] CUDA driver version: 9010
I0910 14:36:29.036089 13312 caffe.cpp:908] Arguments: 
[0]: /home/junxiang/caffe-jacinto/build/tools/caffe.bin
[1]: test_detection
[2]: --model=training/voc0712/JDetNet/20180828_14-57_ds_PSP_dsFac_32_hdDS8_1/test_quantize/test.prototxt
[3]: --iterations=496
[4]: --weights=training/voc0712/JDetNet/20180828_14-57_ds_PSP_dsFac_32_hdDS8_1/sparse/voc0712_ssdJacintoNetV2_iter_120000.caffemodel
…………………………………………

I0910 14:36:48.912307 13312 net.cpp:2195] Enabling quantization at output of: Concat mbox_loc
I0910 14:36:48.912477 13312 net.cpp:2195] Enabling quantization at output of: Concat mbox_conf
I0910 14:36:48.912649 13312 net.cpp:2195] Enabling quantization at output of: Concat mbox_priorbox
I0910 14:36:48.917215 13350 common.cpp:192] New stream 0x7fa3ac006960, device 0, thread 13350
F0910 14:36:48.941680 13312 permute_layer.cu:70] Check failed: error == cudaSuccess (7 vs. 0)  too many resources requested for launch
*** Check failure stack trace: ***
    @     0x7fa4660295cd  google::LogMessage::Fail()
    @     0x7fa46602b433  google::LogMessage::SendToLog()
    @     0x7fa46602915b  google::LogMessage::Flush()
    @     0x7fa46602be1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fa467a7ce48  caffe::PermuteLayer<>::Forward_gpu()
    @     0x7fa4673e8a7f  caffe::Layer<>::Forward()
    @     0x7fa4672561fe  caffe::Net::ForwardFromTo()
    @     0x7fa46725633d  caffe::Net::Forward()
    @           0x44cc4b  test_detection()
    @           0x4521f2  main
    @     0x7fa4647ab830  __libc_start_main
    @           0x449699  _start
    @              (nil)  (unknown)

Can you tell me how to solve this problem？

**Comment by mathmanu** [comment] 2018-10-02 18:41
Duplicate of https://github.com/tidsp/caffe-jacinto/issues/24 
closing.

**Closed as completed by mathmanu** 2018-10-02 18:41 UTC
